#=============================================================================
# File modified from original dark_powered.toml template example
#=============================================================================
[options]
# formatting
    default_indent = 4
    expand_tab = true
    relativenumber = false
# for icons to play nice, make sure to update font for terminal emulator
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
# overriding defaults I don't like
# using 'q' to close active window is not a fun default lol
    windows_smartclose = ''
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    enable_guicolors = true
# buffer configs
    buffer_index_type = 4
# statusline configs
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
# file manager/nerdtree
    filemanager = "nerdtree"
    filetree_direction = "right"
    enable_vimfiler_welcome = true
    enable_vimfiler_filetypeicon = true

# layers
# lang layers
[[layers]]
name = "lang#python"
enable_typeinfo = true
format_on_save = true
enabled_linters = ['python', 'pylint'] 

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#sql"

[[layers]]
name = "lang#json"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "colorscheme"

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 30
enable = true

[[layers]]
name = "ui"
enable_scrollbar = true

[[layers]]
name = "incsearch"

[[layers]]
name = "core#statusline"

[[layers]]
name = "denite"

[[layers]]
name = "gtags"
gtagslabel = "ctags"
auto_update = true

# custom plugins
[[custom_plugins]]
repo = "numirias/semshi"
merged = false 

[[custom_plugins]]
repo = "ryanoasis/vim-devicons"
merged = false
