#=============================================================================
# File modified from original dark_powered.toml template example
#=============================================================================
[options]
    automatic_update = true
# formatting
    default_indent = 4
    expand_tab = true
    relativenumber = false
# for icons to play nice, make sure to update font for terminal emulator
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
# overriding defaults I don't like
    windows_smartclose = ''
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    enable_guicolors = true
# buffer configurations
    buffer_index_type = 4
# status-line configurations
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
# file manager/nerdtree
    filemanager = "nerdtree"
    filetree_direction = "left"
    enable_vimfiler_welcome = true
    enable_vimfiler_filetypeicon = true
# bootstrapping functions
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# layers
# language layers
[[layers]]
    name = "core"
    enable_filetree_gitstatus = true
    enable_filetree_filetypeicon = true

[[layers]]
    name = "core#statusline"
    enabled = true

[[layers]]
    name = "core#tabline"
    enabled = true

[[layers]]
    name = "checkers"
    line_on_the_fly = true
    lint_on_save = true

[[layers]]
    name = "ui"
    enabled_scrollbar = false
    enabled_indentline = false
    cursorword_delay = 200
    cursorword_exclude_filetype = ['markdown']

[[layers]]
    name = "lang#python"
    enable_typeinfo = true
    format_on_save = true
    enabled_linters = ['python', 'pylint'] 
    python_file_head = [
        '# -*- coding: utf-8 -*-',
        '# Author: autodan',
        '# Mail: dpeterson@linevisioninc.com',
        '# Created: `strftime("%a %b %d")` '
        ''
    ]

[[layers]]
    name = "lang#toml"

[[layers]]
    name = "lang#html"

[[layers]]
    name = "lang#json"

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "ui"
    enable_scrollbar = false

[[layers]]
    name = "incsearch"

[[layers]]
    name = "denite"

# [[layers]]
#     name = "gtags"
#     gtagslabel = "ctags"
#     auto_update = true

# custom plugins
[[custom_plugins]]
    repo = "numirias/semshi"
    merged = false 

[[custom_plugins]]
    repo = "ryanoasis/vim-devicons"
    merged = false

[[custom_plugins]]
    repo = "habamax/vim-godot"
    merged = false

[[custom_plugins]]
    repo = "junegunn/fzf"
    merged = false

[[custom_plugins]]
    repo = "junegunn/fzf.vim"
    merged = false
